changes to add assert functions

diff --git a/mac b/mac
--- a/mac
+++ b/mac
@@ -288,9 +288,12 @@ allow_control() {
   fi
 }
 
-# TODO (h4w5) everywhere a variable is used but defined in another file,
-# handle that situation (as with $FORCE here), maybe by defaulting if not
-# set?
+# set FORCE (do not quit on error) to true if it is not loaded, as a default
+: ${FORCE=true}
+
+echo_log() {
+  echo "$1" >&2
+}
 
 # ex: assert_that "`gem` is installed" "gem"
 # ex: assert_that "`gem` is shimmed by rbenv" "which gem" "$HOME/.rbenv/shims/gem"
@@ -302,13 +305,12 @@ allow_control() {
 assert_that() {
   # test for a simple error by evaling the second argument, and redirecting only
   # STDERR to a variable named ERR
-  ERR=$( (eval "$2") 2>&1 >/dev/null )
-  OUT=$(eval "$2")
+  ERR=$( (eval "$2") 2>&1 >/dev/null ) && { export OUT=$(eval "$2"); }
 
   if [ -n "$ERR" ]; then # if ERR is not null, then...
     # echo failure to STDERR & STDOUT
     echo_log "${RED}$1: failure! Error: ${ERR}${RESET}"
-    [-n "$FORCE"] || exit; # exit on failure if not 'forcing'
+    [ -n "$FORCE" ] || exit 1; # exit on failure if not 'forcing'
   elif [ -n "$3" ]; then # else, if there is a third argument...
     if [ "$OUT" = "$3" ]; then # and they equal
       # echo success to STDERR & STDOUT
@@ -316,12 +318,29 @@ assert_that() {
     else
       # echo failure to STDERR & STDOUT if second and third arguments do not match
       echo_log "${RED}$1: failure! '$OUT' does not equal '$3'.${RESET}"
-      [-n "$FORCE"] || exit; # exit on failure if not 'forcing'
+      [ -n "$FORCE" ] || exit 1; # exit on failure if not 'forcing'
     fi
   else
     # echo success to STDERR & STDOUT
     echo_log "${GREEN}$1...${RESET}"
   fi
+}
+
+# ex: assert_package_installed "git"
+# ex: packagelist=( libssl-dev; libcurl4-openssl-dev; git; git-core ); assert_package_installed ${packagelist[@]}
+
+# only works when packages share a name across OSs, otherwise easiest to write
+# two assertions...
+assert_package_installed() {
+  for package in "$@"; do
+    if [ "$OSTYPE" == "darwin" ]; then
+      assert_that "'${package}' package is installed" "brew ls --versions ${package}" "${package}"
+    elif [ "$OSTYPE" == "linux-gnu" ]; then
+      assert_that "'${package}' package is installed" "dpkg -s ${package}"
+    else
+      echo_log "${RED}OS Type unknown in assertions...${RESET}" && exit 1;
+    fi
+  done
 }
 BELOVED_RUBY_VERSION="2.1.2"
 CURRENT_STABLE_RUBY_VERSION="2.1.2"
@@ -333,7 +352,7 @@ INSTALL_REPO=https://github.com/ga-instructors/installfest_script.git
 MINIMUM_OS="10.7.0"
 
 # This refers to the branch of our repo that we are using (for cloning).
-BRANCH=version2
+BRANCH=pj_working
 # Capture the user's password
 sudo echo "Thanks."
 
diff --git a/ubuntu b/ubuntu
--- a/ubuntu
+++ b/ubuntu
@@ -288,9 +288,12 @@ allow_control() {
   fi
 }
 
-# TODO (h4w5) everywhere a variable is used but defined in another file,
-# handle that situation (as with $FORCE here), maybe by defaulting if not
-# set?
+# set FORCE (do not quit on error) to true if it is not loaded, as a default
+: ${FORCE=true}
+
+echo_log() {
+  echo "$1" >&2
+}
 
 # ex: assert_that "`gem` is installed" "gem"
 # ex: assert_that "`gem` is shimmed by rbenv" "which gem" "$HOME/.rbenv/shims/gem"
@@ -302,13 +305,12 @@ allow_control() {
 assert_that() {
   # test for a simple error by evaling the second argument, and redirecting only
   # STDERR to a variable named ERR
-  ERR=$( (eval "$2") 2>&1 >/dev/null )
-  OUT=$(eval "$2")
+  ERR=$( (eval "$2") 2>&1 >/dev/null ) && { export OUT=$(eval "$2"); }
 
   if [ -n "$ERR" ]; then # if ERR is not null, then...
     # echo failure to STDERR & STDOUT
     echo_log "${RED}$1: failure! Error: ${ERR}${RESET}"
-    [-n "$FORCE"] || exit; # exit on failure if not 'forcing'
+    [ -n "$FORCE" ] || exit 1; # exit on failure if not 'forcing'
   elif [ -n "$3" ]; then # else, if there is a third argument...
     if [ "$OUT" = "$3" ]; then # and they equal
       # echo success to STDERR & STDOUT
@@ -316,12 +318,29 @@ assert_that() {
     else
       # echo failure to STDERR & STDOUT if second and third arguments do not match
       echo_log "${RED}$1: failure! '$OUT' does not equal '$3'.${RESET}"
-      [-n "$FORCE"] || exit; # exit on failure if not 'forcing'
+      [ -n "$FORCE" ] || exit 1; # exit on failure if not 'forcing'
     fi
   else
     # echo success to STDERR & STDOUT
     echo_log "${GREEN}$1...${RESET}"
   fi
+}
+
+# ex: assert_package_installed "git"
+# ex: packagelist=( libssl-dev; libcurl4-openssl-dev; git; git-core ); assert_package_installed ${packagelist[@]}
+
+# only works when packages share a name across OSs, otherwise easiest to write
+# two assertions...
+assert_package_installed() {
+  for package in "$@"; do
+    if [ "$OSTYPE" == "darwin" ]; then
+      assert_that "'${package}' package is installed" "brew ls --versions ${package}" "${package}"
+    elif [ "$OSTYPE" == "linux-gnu" ]; then
+      assert_that "'${package}' package is installed" "dpkg -s ${package}"
+    else
+      echo_log "${RED}OS Type unknown in assertions...${RESET}" && exit 1;
+    fi
+  done
 }
 BELOVED_RUBY_VERSION="2.1.2"
 CURRENT_STABLE_RUBY_VERSION="2.1.2"
@@ -332,7 +351,7 @@ SETTINGS=$SRC_DIR/settings
 INSTALL_REPO=https://github.com/ga-instructors/installfest_script.git
 
 # This refers to the branch of our repo that we are using (for cloning).
-BRANCH=version2
+BRANCH=pj_working
 # Capture the user's password
 sudo echo "Thanks."
 
@@ -340,13 +359,14 @@ sudo echo "Thanks."
 while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
 
 # TODO (phlco) does this actually work?
+
 #-------------------------------------------------------------------------------
 # Check for software updates
 #-------------------------------------------------------------------------------
+
 sudo apt-get -y update
 sudo apt-get -y upgrade
 sudo apt-get -y dist-upgrade
-# TODO (phlco) reboot?
 packagelist=(
   # Autoconf is an extensible package of M4 macros that produce shell scripts to automatically configure software source code packages.
   autoconf
@@ -380,7 +400,6 @@ packagelist=(
 
   # OpenSSL implementation of SSL
   libssl-dev
-
   libcurl4-openssl-dev
 
   # version control
@@ -392,10 +411,12 @@ packagelist=(
 
   # command line tool for transferring data with URL syntax
   curl
+
   # This software provides an abstraction of the used apt repositories.
   python-software-properties
 
-  # required for building Debian packages
+  # a reference for all the packages needed to compile a debian package
+  # generally includes the gcc/g++ compilers an libraries and some other utils
   build-essential
 
   # library implementing the deflate compression method found in gzip and PKZIP
@@ -411,7 +432,6 @@ packagelist=(
 
   # self-contained, serverless, transactional SQL database engine.
   sqlite3
-
   libsqlite3-dev
 
   # ASCII ART!!!!
@@ -453,10 +473,8 @@ echo '- Confirm the action by entering your GitHub password'
 
 pause_awhile "Press Enter. We'll be here until you get back from Github."
 
-echo "Firefox may print an error to the terminal. DON'T WORRY!"
 # Open in default browser as a new process
-# FIXME(phlco) Firefox raises an error
-# directing output to /dev/null to supress error
+echo "Firefox may print an error to the terminal. DON'T WORRY!" # directing output to /dev/null to supress error
 xdg-open https://github.com/settings/ssh 2>/dev/null
 
 pause_awhile "Ok. Ready to Continue? Press Enter."
@@ -510,16 +528,14 @@ git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
 export PATH="$HOME/.rbenv/bin:$PATH"
 eval "$(rbenv init -)"
 
-# FIXME (h4w5) should check if it exists
-# Wouldn't it not exist until installing rbenv anyway?
+# FIXME (h4w5) i meant to put in an assertion here...
+
 # Specify default gems in ~/.rbenv/default-gems
 git clone https://github.com/sstephenson/rbenv-default-gems.git ~/.rbenv/plugins/rbenv-default-gems
 
 # automatically runs rbenv rehash every time you install or uninstall a gel.
 git clone https://github.com/sstephenson/rbenv-gem-rehash.git ~/.rbenv/plugins/rbenv-gem-rehash
 
-# FIXME (h4w5) should check if it exists
-# Wouldn't it not exist until installing rbenv anyway?
 # Provides an rbenv install command to compile and install different versions of Ruby
 git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
 # Our gems to install
