updates ubuntu

diff --git a/ubuntu b/ubuntu
--- a/ubuntu
+++ b/ubuntu
@@ -37,6 +37,365 @@ mkdir -p ~/.wdi; exec > >(tee ~/.wdi/install.log); exec 2>&1
 
 echo "Script executed at $(date)"
 echo ""
+
+#-------------------------------------------------------------------------------
+# Set text formatting
+#-------------------------------------------------------------------------------
+
+# Reset formatting
+RESET=$(      tput sgr0)
+
+# Foreground color
+BLACK=$(      tput setaf 0)
+RED=$(        tput setaf 1)
+GREEN=$(      tput setaf 2)
+YELLOW=$(     tput setaf 3)
+BLUE=$(       tput setaf 4)
+MAGENTA=$(    tput setaf 5)
+CYAN=$(       tput setaf 6)
+WHITE=$(      tput setaf 9)
+# ORANGE=$(     tput setaf 172)
+# PURPLE=$(     tput setaf 141)
+
+# Background color
+BG_BLACK=$(   tput setab 0)
+BG_RED=$(     tput setab 1)
+BG_GREEN=$(   tput setab 2)
+BG_YELLOW=$(  tput setab 3)
+BG_BLUE=$(    tput setab 4)
+BG_MAGENTA=$( tput setab 5)
+BG_CYAN=$(    tput setab 6)
+BG_WHITE=$(   tput setab 9)
+# BG_ORANGE=$(  tput setab 172)
+
+# Style
+UNDERLINE=$(  tput smul)
+NOUNDERLINE=$(tput rmul)
+BOLD=$(       tput bold)
+ITALIC=$(     tput sitm)
+
+#-------------------------------------------------------------------------------
+# Functions
+#-------------------------------------------------------------------------------
+
+#######################################
+# ABRB
+# Arguments:
+#   Message
+#   Attribution
+# Returns:
+#   None
+#######################################
+function quoth_the_bard () {
+  local message=$1
+  local attribution=$2
+  echo ""
+  echo "$YELLOW$message$RESET"
+  echo "$PURPLE$attribution$RESET"
+}
+
+#######################################
+# Upcase error message and exit script
+# Arguments:
+#   Error message
+# Returns:
+#   None
+#######################################
+
+function fie () {
+  local message=$(echo $1 | tr 'a-z' 'A-Z')
+  echo ""
+  echo "$RED$message$RESET"
+  exit
+}
+
+
+#######################################
+# Announce our acts
+# Arguments:
+#   Act Number
+# Returns:
+#   None
+#######################################
+function figlet_announces () {
+  clear
+  local act=$1
+  figlet -f ogre $act
+}
+
+#######################################
+# Waits for user input
+# Arguments:
+#   Message
+# Returns:
+#   None
+#######################################
+function pause_awhile () {
+   read -p "$* Press Enter to continue"
+}
+
+#######################################
+# Mounts DMG and moves to Applications
+# Arguments:
+#   File name
+# Returns:
+#   None
+#######################################
+function install_dmg () {
+  echo 'Hark, a dmg!'
+  file_name="$1"
+  MOUNTPOINT="/Volumes/MountPoint"
+  IFS="
+  "
+  hdiutil attach -mountpoint $MOUNTPOINT "$file_name.dmg"
+  app=$(find $MOUNTPOINT 2>/dev/null -maxdepth 2 -iname \*.app)
+  if [[ ! -z "$app" ]]; then
+    cp -a "$app" /Applications/
+  fi
+  echo 'Hark! A pkg!'
+  pkg=$(find $MOUNTPOINT 2>/dev/null -maxdepth 2 -iname \*.pkg)
+  if [[ ! -z "$pkg" ]]; then
+    # PL: Need to handle harddrive names that aren't Macintosh HD
+    sudo installer -package $pkg -target /
+  fi
+  hdiutil detach $MOUNTPOINT
+}
+
+#######################################
+# Unzip Zip and move App to Applications
+# Arguments:
+#   File name
+# Returns:
+#   None
+#######################################
+function install_zip () {
+  file_name="$1"
+  echo 'Hark! A zip!'
+  mkdir "$file_name"
+  unzip "$file_name.zip" -d "$file_name"
+  mv $file_name/*.app /Applications
+}
+
+#######################################
+# Checks for the existence of a file
+# Arguments:
+#   File name
+# Returns:
+#   1 or 0
+#######################################
+function know_you_not_of () {
+  file_name="$1"
+  file_count=$(find /Applications -name "$file_name.app" | wc -l)
+  if [[ $file_count -gt 0 ]]; then
+    echo "$file_name is already here.";
+    return 1
+  else
+    return 0
+  fi
+}
+
+#######################################
+# Downloads and installs apps from zips, dmgs, and pkgs.
+# Arguments:
+#   File name
+#   URL
+# Returns:
+#   None
+#######################################
+function lend_me_your () {
+  file_name="$1"
+  url="$2"
+  ext=${url: -4}
+  if know_you_not_of "$file_name" ; then
+    curl -L -o "$file_name$ext" $url
+    # enter stage left...
+    case "$ext" in
+      ".dmg")  install_dmg "$file_name";;
+      ".zip")  install_zip "$file_name";;
+      *) echo "Not Processed";;
+    esac
+  fi
+  # Out spot
+  rm -rf "$file_name$ext"
+  rm -rf "$file_name"
+}
+
+#######################################
+# Allow apps to control your computer
+# Arguments:
+#   File name
+# Returns:
+#   None
+#######################################
+allow_control() {
+  if [[ "$OSTYPE" =~ ^darwin13.*$ ]]; then
+    for app; do
+      APP_ID="$(osascript -e "id of app \"$app\"")"
+      if [[ -n "$APP_ID" ]]; then
+        sudo sqlite3 /Library/Application\ Support/com.apple.TCC/TCC.db "INSERT or REPLACE INTO access values ('kTCCServiceAccessibility', '$APP_ID', 0, 1, 0, NULL);"
+      fi
+    done
+  else
+    echo "allow_control works only on Mavericks"
+  fi
+}
+# Capture the user's password
+sudo echo "Thanks."
+
+# Update existing `sudo` time stamp until script has finished
+while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &
+
+# TODO (philco) does this actually work?
+#-------------------------------------------------------------------------------
+# Check for software updates
+#-------------------------------------------------------------------------------
+sudo apt-get -y update
+sudo apt-get -y upgrade
+sudo apt-get -y dist-upgrade
+# TODO (phlco) reboot?
+BELOVED_RUBY_VERSION="2.1.2"
+CURRENT_STABLE_RUBY_VERSION="2.1.2"
+
+# TODO backport this into master and mac...
+SRC_DIR=~/.wdi/installfest
+SETTINGS=$SRC_DIR/settings
+INSTALL_REPO=https://github.com/ga-instructors/installfest_script.git
+
+# This refers to the branch of our repo that we are using (for cloning).
+BRANCH=version2
+# Autoconf is an extensible package of M4 macros that produce shell scripts to automatically configure software source code packages.
+sudo apt-get -y install autoconf
+
+# Automake is a tool for automatically generating Makefile.in
+sudo apt-get -y install automake
+
+# general-purpose parser generator that converts an annotated context-free grammar into an LALR or GLR parser for that grammar.
+sudo apt-get -y install bison
+
+# generic library support script
+sudo apt-get -y install libtool
+
+# a YAML 1.1 parser and emitter
+sudo apt-get -y install libyaml-dev
+
+# provides a set of functions for use by applications that allow users to edit command lines as they are typed in
+sudo apt-get -y install libreadline6 libreadline6-dev
+
+# XML C parser and toolkit
+sudo apt-get -y install libxml2-dev
+
+# a language for transforming XML documents into other XML documents.
+sudo apt-get -y install libxslt1-dev
+
+# gnome-keyring is a daemon in the session, similar to ssh-agent,
+# and other applications can use it to store passwords and other
+# sensitive information
+# atom dependency?
+sudo apt-get -y install libgnome-keyring-dev
+
+# OpenSSL implementation of SSL
+sudo apt-get -y install libssl-dev
+
+# git for version control
+sudo apt-get -y install git
+
+# copy to clipboard
+sudo apt-get -y install xclip
+
+# generates an index file of names found in source files of various programming languages.
+sudo apt-get -y install exuberant-ctags
+
+# ASCII ART!!!!
+sudo apt-get -y install figlet
+
+# visualization tool for ERDs
+sudo apt-get -y install graphviz
+
+# image resizing
+sudo apt-get -y install imagemagick
+
+# PhantomJS is a headless WebKit scriptable with a JavaScript API.
+sudo apt-get -y install phantomjs
+
+# a self-contained, serverless, zero-configuration, transactional SQL database engine.
+
+# extras
+# TODO (phlco) consolidate these
+sudo apt-get -y install git-core
+sudo apt-get -y install curl
+sudo apt-get -y install sudo apt-get install -y
+sudo apt-get -y install sudo apt-get -y install sqlite3
+sudo apt-get -y install libsqlite3-dev
+sudo apt-get -y install libcurl4-openssl-dev
+sudo apt-get -y install python-software-properties
+sudo apt-get -y install libreadline-dev
+sudo apt-get -y install build-essential
+sudo apt-get -y install zlib1g-dev
+echo "Please register for an account on github.com if you haven't already done so."
+
+read -p "Enter your full name: "  user_name
+read -p "Github Username: "       github_name
+read -p "Github Email: "          github_email
+# SSH Keygen
+ssh-keygen -t rsa -C $github_email
+ssh-add id_rsa
+
+# Copy SSH key to the clipboard
+cat ~/.ssh/id_rsa.pub | xclip -selection clipboard
+
+echo "We just copied your SSH key to the clipboard."
+echo "Now we're going to visit GitHub to add the SSH key"
+
+echo "Do the following in your browser: "
+echo '- Click "SSH Keys" in the left sidebar'
+echo '- Click "Add SSH key"'
+echo '- Set the Title to WDI Installfest'
+echo '- Paste your key into the "Key" field'
+echo '- Click "Add key"'
+echo '- Confirm the action by entering your GitHub password'
+
+pause_awhile "Press Enter. We'll be here until you get back from Github."
+
+echo "Firefox may print an error to the terminal. DON'T WORRY!"
+# Open in default browser as a new process
+# TODO(phlco) Firefox raises an error
+xdg-open https://github.com/settings/ssh &
+
+pause_awhile "Ok. Ready to Continue? Press Enter."
+# Add user's github info to gitconfig
+# https://www.kernel.org/pub/software/scm/git/docs/git-config.html
+git config --global user.name  $github_name
+git config --global user.email $github_email
+
+# set olors
+git config --global color.ui always
+
+git config --global color.branch.current   "green reverse"
+git config --global color.branch.local     green
+git config --global color.branch.remote    yellow
+
+git config --global color.status.added     green
+git config --global color.status.changed   yellow
+git config --global color.status.untracked "red blink"
+
+# set editor
+git config --global core.editor "subl -w"
+
+# default branch to push to
+git config --global push.default current
+# download the repo for the absolute paths
+if [[ ! -d $SRC_DIR ]]; then
+  echo 'Downloading Installfest repo...'
+  # autoupdate bootstrap file
+  git clone -b $BRANCH $INSTALL_REPO $SRC_DIR
+  # hide folder
+  # chflags hidden $SRC_DIR # FIXME (h4w5) doesn't work on linux
+else
+  # update repo
+  echo 'Updating repo...'
+  cd $SRC_DIR
+  git pull origin $BRANCH
+fi
 # Because we're going to use rbenv and homebrew we need to remove RVM and MacPorts
 # This script checks for and removes previous installs of macports and RVM
 
@@ -60,6 +419,236 @@ fi
 # ls -d ~/.bundle*
 # # Delete them (ignoring those that don't exist)
 # rm -rf ~/.rvm* ~/.gem/ ~/.bundle*
+# # our ruby version manager
+# sudo apt-get -y install rbenv
+# # git clone git://github.com/sstephenson/rbenv.git ~/.rbenv
+# # provides an `rbenv install` command
+# sudo apt-get -y install ruby-build
+#
+# # ruby_check=$(rbenv versions | grep $BELOVED_RUBY_VERSION)
+# #
+# # if [[ "$ruby_check" == *$BELOVED_RUBY_VERSION* ]]; then
+# #   echo "$BELOVED_RUBY_VERSION is installed"
+# # else
+# #   rbenv install $BELOVED_RUBY_VERSION
+# # fi
+#
+#
+# # TODO (h4w5) must come to understand this...
+#
+# source $HOME/.bashrc
+
+git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
+
+export PATH="$HOME/.rbenv/bin:$PATH"'
+eval "$(rbenv init -)"'
+
+git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
+ruby_check=$(rbenv versions | grep $BELOVED_RUBY_VERSION)
+
+if [[ "$ruby_check" == *$BELOVED_RUBY_VERSION* ]]; then
+  echo "$BELOVED_RUBY_VERSION is installed"
+else
+  rbenv install $BELOVED_RUBY_VERSION
+fi
+
+rbenv rehash
+
+source ~/.bashrc
+# echo "${BOLD}Ruby version is now: '`ruby -v`'...${RESET}"
+# echo "${BOLD}Ruby now found at: `which ruby`...${RESET}"
+#
+# echo "${BOLD}Setting the global ruby as '${BELOVED_RUBY_VERSION}'...${RESET}"
+
+rbenv global $BELOVED_RUBY_VERSION
+
+# echo "${BOLD}Ruby version is now: '`ruby -v`'...${RESET}"
+# echo "${BOLD}Ruby now found at: `which ruby`...${RESET}"
+#
+# echo "${BOLD}Adding the rbenv binary directory to path, and prepending the .shims...${RESET}"
+
+# rbenv rehash # happens at end of eval above I believe (h4w5)
+
+# echo "${BOLD}Path is now:${RESET} ${PATH}"
+# echo "${BOLD}Ruby version is now: '`ruby -v`'...${RESET}"
+# echo "${BOLD}Ruby now found at: `which ruby`...${RESET}"
+
+# echo "${BOLD}Path is now:${RESET} ${PATH}"
+# echo "${BOLD}Ruby version is now: '`ruby -v`'...${RESET}"
+# echo "${BOLD}Ruby now found at: `which ruby`...${RESET}"
+# echo "${BOLD}Gem environment is now:${RESET}"
+# gem env
+
+# export PATH="$HOME/.rbenv/bin:$PATH"
+# eval "$(rbenv init -)"
+
+# For testing and simplicity with Ubuntu, add these to the .bashrc until it's
+# overwritten...
+echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ~/.bashrc
+echo 'eval "$(rbenv init -)"' >> ~/.bashrc
+
+source ~/.bashrc
+# Our gems to install
+
+echo "gem: --no-ri --no-rdoc" > ~/.gemrc
+
+# Maintains a consistent environment for ruby applications.
+gem install bundler
+
+# Acceptance test framework for web applications
+gem install capybara
+
+# handle events on file system modifications
+gem install guard
+
+# JavaScript testing
+gem install jasmine
+
+# ruby interface for Postgres
+gem install pg
+
+# alternative to the standard IRB shell
+gem install pry
+
+# live syntax highlighting for the Pry REPL
+gem install pry-coolline
+
+# full stack, Web application framework
+gem install rails
+
+# testing tool for Ruby
+gem install rspec
+
+# a DSL for quickly creating web applications in Ruby
+gem install sinatra
+
+# common Sinatra extensions
+gem install sinatra-contrib
+
+# Ruby interface to github API v3
+gem install github_api
+
+# HipChat HTTP API Wrapper
+gem install hipchat
+
+# pretty print your Ruby objects with style
+gem install awesome_print
+
+# colorizing printed text on ANSI terminals
+gem install rainbow
+# Event-driven I/O server-side JavaScript environment based on V8
+sudo apt-get -y install nodejs
+
+# Node package manager
+sudo apt-get -y install npm
+
+# For programs that still depend on calling the "node" binary, run:
+sudo apt-get -y install nodejs-legacy
+# Google Chrome.........The Browser
+# HipChat...............The Chat Client
+# Sublime Text 2........The Text Editor
+
+# chrome
+wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
+sudo sh -c 'echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list'
+sudo apt-get -y update
+sudo apt-get -y install google-chrome-stable
+
+# hipchat
+echo "deb http://downloads.hipchat.com/linux/apt stable main" > /etc/apt/sources.list.d/atlassian-hipchat.list
+wget -O - https://www.hipchat.com/keys/hipchat-linux.key | apt-key add -
+sudo apt-get -y update
+sudo apt-get -y install hipchat
+
+# sublime
+sudo add-apt-repository -y ppa:webupd8team/sublime-text-2
+sudo apt-get -y update
+sudo apt-get -y install sublime-text
+
+# zsh
+sudo apt-get -y install zsh
+
+# flux
+sudo add-apt-repository -y ppa:kilian/f.lux
+sudo apt-get -y update
+sudo apt-get -y install fluxgui
+
+# hub
+# http://eoinoc.net/install-hub-github-linux-mint/
+curl http://defunkt.io/hub/standalone -Lo ~/usr/bin/hub
+chmod 755 ~/usr/bin/hub
+
+# vim
+sudo apt-get -y install vim
+# Heroku command-line tooling for working with the Heroku platform
+
+# http://eoinoc.net/install-hub-github-linux-mint/
+wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
+
+# https://devcenter.heroku.com/articles/keys
+echo "Heroku is a cloud platform as a service (PaaS) supporting several"
+echo "programming languages."
+
+echo "If you don’t already use SSH, you’ll need to create a public/private key"
+echo "pair to deploy code to Heroku. This keypair is used for the strong"
+echo "cryptography and that uniquely identifies you as a developer when pushing"
+echo "code changes."
+
+ssh-keygen -t rsa
+
+echo "The first time you run the heroku command, you’ll be prompted for your "
+echo "credentials. Your public key will then be automatically uploaded to"
+echo "Heroku. This will allow you to deploy code to all of your apps."
+echo "Please enter your email"
+
+heroku keys:add
+# open source object-relational database management system
+# https://www.digitalocean.com/community/articles/how-to-install-and-use-postgresql-on-ubuntu-12-04
+# TODO phlco set up user
+# https://help.ubuntu.com/community/PostgreSQL
+# sudo apt-get -y install postgresql-xc-client
+# sudo apt-get -y install postgresql-client
+# sudo apt-get -y install postgresql
+# sudo apt-get -y install postgresql-contrib
+# sudo apt-get -y install pg_ctl # initialize stop/start posgres
+sudo apt-get -y install postgresql
+sudo apt-get -y install postgresql-contrib
+
+sudo -u postgres createuser --superuser $USER
+# TODO phlco. taking out?
+# sudo -u postgres psql
+# create a history?
+touch ~/.psql_history
+
+createdb $USER
+# Install Vim Plugin Manager
+git clone https://github.com/gmarik/Vundle.vim.git ~/.vim/bundle/Vundle.vim
+
+# Vimrc is copied over from dotfiles
+# The Z shell (zsh) is a Unix shell that can be used as an interactive login
+# shell and as a powerful command interpreter for shell scripting. Zsh can be
+# thought of as an extended Bourne shell with a large number of improvements,
+# including some features of bash, ksh, and tcsh.
+# This script installs zsh, oh-my-zsh, an open source, community-driven framework
+# for managing your ZSH configuration.
+
+# Install zsh
+git clone git://zsh.git.sf.net/gitroot/zsh/zsh
+cp ~/.zshrc ~/.zshrc.orig
+
+# Install oh-my-zsh
+git clone git://github.com/robbyrussell/oh-my-zsh.git ~/.oh-my-zsh
+cp $SRC_DIR/settings/dotfiles/zshrc ~/.zshrc
+
+# Syntax Highlighting
+git clone git://github.com/zsh-users/zsh-syntax-highlighting.git ~/.oh-my-zsh/custom/plugins
+
+# Set as default
+chsh -s /bin/zsh
+
+# Resources
+# https://github.com/robbyrussell/oh-my-zsh
+# http://www.stevendobbelaere.be/installing-and-configuring-the-oh-my-zsh-shell/
 # Don't ask questions
 export DEBIAN_FRONTEND=noninteractive
 sudo apt-get install -y mailutils
